MODULE StoreTaskSettings;

NAMESPACE StoreTask;

FORM options 'Настройки';

DESIGN options {
    OBJECTS {
        NEW tabbedPane {
            tabbed = TRUE;
            fill = 1;
            NEW commons {
                caption = 'Основное';
            }
        }
    }
}

NAVIGATOR {
    NEW FOLDER storeTask 'Задачи магазинов' WINDOW toolbar IMAGE 'retail.png' {
        NEW FOLDER operations 'Операции' {
        }
        NEW FOLDER catalogs 'Справочники' {
        }
        NEW FOLDER settings 'Настройка' {
            NEW options;
        }
    }
}
