MODULE SimpleExecutionMobile;

REQUIRE SimpleExecution, StoreTaskMobile;

NAMESPACE StoreTask;

FORM simpleMobile 'Выполнение'
    OBJECTS e = SimpleExecution PANEL
    PROPERTIES(e) nameObject READONLY, nameType READONLY, nameState READONLY,
        photo, comment,
        finish
;

DESIGN simpleMobile {
    OBJECTS {
        NEW head {
            alignment = STRETCH;
            MOVE PROPERTY(nameObject(e)) { fontSize = 18; }
            NEW headLine {
                horizontal = TRUE;
                alignment = STRETCH;
                MOVE PROPERTY(nameType(e));
                MOVE PROPERTY(nameState(e));
            }
        }
        NEW body {
            fill = 1;
            alignment = STRETCH;
            MOVE PROPERTY(photo(e)) { valueHeight = 260; valueWidth = 260; }
            MOVE PROPERTY(comment(e));
        }
        MOVE PROPERTY(finish(e)) { fontSize = 16; }
    }
}

openMobileExecution(SimpleExecution e) + {
    SHOW simpleMobile OBJECTS e = e DOCKED NEWSESSION;
}
