MODULE StoreTaskTag;

REQUIRE StoreTaskSettings, StoreTaskColor;

NAMESPACE StoreTask;

CLASS TaskTag 'Метка задачи';
name '{Name}' = DATA ISTRING[50] (TaskTag) NONULL CHARWIDTH 15;

id '{ID}' = DATA STRING[20] (TaskTag);
taskTag = GROUP AGGR TaskTag t BY id(t);

color 'Цвет' = DATA TaskColor (TaskTag);
nameColor 'Цвет' (TaskTag p) = name(color(p));
idColor 'Цвет' (TaskTag p) = id(color(p));

FORM taskTag 'Метка задачи'
    OBJECTS o = TaskTag PANEL
    PROPERTIES(o) name, id, nameColor

    EDIT TaskTag OBJECT o;
;

DESIGN taskTag {
    OBJECTS {
        NEW tabbedPane {
            fill = 1;
            tabbed = TRUE;
        }
    }
}

FORM taskTags 'Метки задач'
    OBJECTS o = TaskTag
    PROPERTIES(o) READONLY name, id, nameColor
    LIST TaskTag OBJECT o
;

EXTEND FORM options
    OBJECTS tg = TaskTag
    PROPERTIES(tg) READONLY name, id, nameColor
    PROPERTIES(tg) NEWSESSION NEW, EDIT, DELETE
;

DESIGN options {
    tabbedPane {
        MOVE BOX(tg) { caption = 'Метки задач'; }
    }
}
